### ISSUE TITLE
Missing columns in repeat groups

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/formpack#138] opened 2017-11-03 17:19 UTC
Forms with repeat groups are missing some columns when exporting data. For test case see [this project](https://kf.kobotoolbox.org/forms/#/forms/a9oXxizqC4rZxnzVgntYgg/data/downloads?export-test). 
For example, the part highlighted in yellow is missing from kc-formpack (whereas it is included in kc-legacy XLS):

![image](https://user-images.githubusercontent.com/673511/32386993-732b1748-c099-11e7-8e37-6689bee1acd8.png)

See FD discussion[here](https://www.flowdock.com/app/kobotoolbox/kobo/threads/QQbvcC1-4s_sU2x_fGMIk5Krdx6).

This requires https://github.com/kobotoolbox/kpi/issues/1465 to be fixed first in the new kpi-formpack export code.

**Comment by jnm** [comment] 2017-12-19 20:28
Duplicate of https://github.com/kobotoolbox/kpi/issues/1348! SO HAPPY.
![giphy](https://user-images.githubusercontent.com/2085013/34175515-a85b2782-e4ca-11e7-9a0a-b2be067c5d6c.gif)

@tinok, all the blank columns in the KPI-formpack export of `a9oXxizqC4rZxnzVgntYgg` (tested with [bleeding-edge code](https://github.com/kobotoolbox/kpi/commit/d312b9549e1ddcdaca5a1c28c1b00eb91b43f07f)) have dots in their XML names ([analysis](https://github.com/kobotoolbox/formpack/files/1573121/formpack.issue.138.analysis.xlsx)).

However, there are some columns in the KC-legacy export that are just entirely missing from the KPI-formpack export, namely:

worksheet | xml name in kc-legacy export | non-empty cells in kc-legacy export
-- | -- | --
main | consentgroup/KAP_B2.myanmar/other | 31
main | consentgroup/KAP_B2.myanmar_other | 8
main | consentgroup/training_myanmar_count | 37
main | consentgroup/KAP_B11.myanmar/other | 13
main | consentgroup/KAP_B11.myanmar_other | 2
main | consentgroup/drills_myanmar_count | 37
main | consentgroup/myanmar_network_count | 37
main | _version__002 | 37
main | meta/instanceID | 37
main | _parent_table_name | 0
main | _parent_index | 37
main | _tags | 0
main | _notes | 0
training | _id | 0
training | _uuid | 0
training | _submission_time | 0
training | _tags | 0
training | _notes | 0
drills | _id | 0
drills | _uuid | 0
drills | _submission_time | 0
drills | _tags | 0
drills | _notes | 0
network | _id | 0
network | _uuid | 0
network | _submission_time | 0
network | _tags | 0
network | _notes | 0

**Comment by tinok** [comment] 2017-12-20 17:19
@jnm Thanks for this exhaustive investigation. I just double checked to confirm:
* `or_other` columns are missing. Added as bug https://github.com/kobotoolbox/formpack/issues/140
* data for variables with `.` in the name _were_ missing. I'm no longer able to reproduce this issue as direct kpi exports [from this project](https://kf.kobotoolbox.org/forms/#/forms/a9oXxizqC4rZxnzVgntYgg/data/downloads) now contain all the relevant data as far as I can tell...

**Comment by jnm** [comment] 2017-12-20 17:40
> data for variables with . in the name were missing. I'm no longer able to reproduce this

There was some confusion when testing KPI-formpack vs. KC-formpack, where the latter does not suffer from https://github.com/kobotoolbox/kpi/issues/1348

**Closed by jnm** 2017-12-20 17:40 UTC
Labels: bug
